name: RecycleHub
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  url_launcher: ^6.3.1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  logging: ^1.3.0
  flutter_screenutil: ^5.9.3
  file_picker: ^10.2.0
  firebase_storage: ^12.4.5
  google_maps_flutter: ^2.12.1
  fl_chart: ^0.70.2
  flutter_launcher_icons: ^0.14.3
  mime: ^2.0.0
  carousel_slider: ^5.0.0
  shared_preferences: ^2.5.3

  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/icons/
     - assets/images/
     - assets/translation.json

  generate: true

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/Recycling_sign_green.png"

